name: DungeonMazeApiTest
main: com.timvisee.dungeonmazeapitest.DungeonMazeApiTest
version: 0.1
depend: [DungeonMaze]
commands:
  dmapitest:
    description: Dungeon Maze API Test command
    usage: /dmapitest
  dungeonmazeapitest:
    description: Dungeon Maze API Test command
    usage: /dungeonmazeapitest